#! /bin/sh
# /etc/init.d/rslsync
#

# Carry out specific functions when asked to by the system
case "$1" in
start)
    /home/pi/.rslsync/rslsync --config /home/pi/.rslsync/rslsync.conf
    ;;
stop)
    killall rslsync
    ;;
*)
    echo "Usage: /etc/init.d/rslsync {start|stop}"
    exit 1
    ;;
esac

exit 0
